In [6]:
import numpy

In [7]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n)

numpy.ndarray

In [13]:
n                # 1d array  
n.reshape(3,9)   # 2d array
n.reshape(3,3,3) # 3d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [16]:
m = numpy.asarray([[123,12,33,13,23],[],[]])  # converts list into numpy array
m

array([list([123, 12, 33, 13, 23]), list([]), list([])], dtype=object)

In [19]:
type(m)

numpy.ndarray

In [2]:
import cv2

In [3]:
img = cv2.imread("gray.png",0)  # 0 for grayscale 1 for BGR
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
cv2.imwrite("new_img.png",img)  #creating img using array values

True

In [26]:
import os
os.listdir()

['.ipynb_checkpoints', 'gray.png', 'new_img.png', 'NumpyOpencv.ipynb']

In [4]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
#  Horizontal stacking. takes 2 or more args
hsimg = numpy.hstack((img,img))
print(hsimg)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [8]:
#  vertical stackin
vsimg = numpy.vstack((img,img))
print(vsimg)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [35]:
# Horizontal splitting 
abc = numpy.hsplit(img,5)  #  It will split numpy array into python lists
print(abc)
type(abc)

[array([[187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182]], dtype=uint8)]


list

In [40]:
# Vertical splitting 
pqr = numpy.vsplit(img,3)  #  It will split numpy array into python lists
pqr

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]